
* Kinematic Cuts 
** tau
*** Elastic production
1e6 events (211pb):
745 had M(l+l-) > 110            --> 157 fb
194 had M(l+l-) > 110 && Pt > 33 --> 41  fb
169 had M(l+l-) > 110 && Pt > 38 --> 36  fb
125 had M(l+l-) > 110 && Pt > 50 --> 26  fb

13 had M(l+l-) > 400             --> 3   fb
2 had M(l+l-) > 400 && Pt > 33   --> 0.4 fb
2 had M(l+l-) > 400 && Pt > 38   --> 0.4 fb
1 had M(l+l-) > 400 && Pt > 50   --> 0.2 fb

5e5 events with *E>20 Pt>10* for both(1.27pb):
 had M(l+l-) > 110                                   --> 74 fb
 had M(l+l-) > 110 && Pt > 33                        --> 38  fb
 had M(l+l-) > 110 && Pt > 38                        --> 33  fb
 had M(l+l-) > 110 && Pt > 50                        --> 22  fb
 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 16  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 22  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 16  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 22  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 16  fb


 had M(l+l-) > 400             -->  2.3 fb
 had M(l+l-) > 400 && Pt > 33  -->  1.5 fb
 had M(l+l-) > 400 && Pt > 38  -->  1.4 fb
 had M(l+l-) > 400 && Pt > 50  -->  1.2 fb

*** Disassociating production
3.5e5 events (132pb):
596 had M(l+l-) > 110            --> 225 fb
154 had M(l+l-) > 110 && Pt > 33 --> 58  fb
135 had M(l+l-) > 110 && Pt > 38 --> 51  fb
79 had M(l+l-) > 110 && Pt > 50  --> 30  fb

13 had M(l+l-) > 400             --> 5   fb
6 had M(l+l-) > 400 && Pt > 33   --> 2   fb
6 had M(l+l-) > 400 && Pt > 38   --> 2   fb
6 had M(l+l-) > 400 && Pt > 50   --> 2   fb

5e5 events with *E>20 Pt>10* for both(1.36pb):
 had M(l+l-) > 110                                   --> 113 fb
 had M(l+l-) > 110 && Pt > 33                        --> 57  fb
 had M(l+l-) > 110 && Pt > 38                        --> 49  fb
 had M(l+l-) > 110 && Pt > 50                        --> 33  fb
 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 24  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 17  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 12  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 15  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 10  fb


 had M(l+l-) > 400             -->  4.0 fb
 had M(l+l-) > 400 && Pt > 33  -->  2.8 fb
 had M(l+l-) > 400 && Pt > 38  -->  2.6 fb
 had M(l+l-) > 400 && Pt > 50  -->  2.4 fb

** muon
*** Elastic production
1e6 events with E>3 Pt>1 for both (399pb):
452 had M(l+l-) > 110            --> 180 fb
111 had M(l+l-) > 110 && Pt > 33 --> 44  fb
97  had M(l+l-) > 110 && Pt > 38 --> 39  fb
77  had M(l+l-) > 110 && Pt > 50 --> 31  fb

6 had M(l+l-) > 400
3 had M(l+l-) > 400 && Pt > 33
3 had M(l+l-) > 400 && Pt > 38
3 had M(l+l-) > 400 && Pt > 50

5e5 events with *E>20 Pt>10* for both(1.28pb):
 had M(l+l-) > 110                                   --> 69 fb
 had M(l+l-) > 110 && Pt > 33                        --> 36  fb
 had M(l+l-) > 110 && Pt > 38                        --> 31  fb
 had M(l+l-) > 110 && Pt > 50                        --> 21  fb
 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 15  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 21  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 15  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 22  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 15  fb


 had M(l+l-) > 400             -->  2.3 fb
 had M(l+l-) > 400 && Pt > 33  -->  1.5 fb
 had M(l+l-) > 400 && Pt > 38  -->  1.4 fb
 had M(l+l-) > 400 && Pt > 50  -->  1.2 fb
*** Disassociating production
1e6 events with *E>3 Pt>1* for both(182pb):
1467 had M(l+l-) > 110           --> 267 fb
376 had M(l+l-) > 110 && Pt > 33 --> 68  fb
312 had M(l+l-) > 110 && Pt > 38 --> 57  fb
171 had M(l+l-) > 110 && Pt > 50 --> 31  fb

26 had M(l+l-) > 400             --> 5   fb
10 had M(l+l-) > 400 && Pt > 33  --> 2   fb
10 had M(l+l-) > 400 && Pt > 38  --> 2   fb
4 had M(l+l-) > 400 && Pt > 50   --> 1   fb

5e5 events with *E>20 Pt>10* for both(1.37pb):
 had M(l+l-) > 110                                   --> 108 fb
 had M(l+l-) > 110 && Pt > 33                        --> 56  fb
 had M(l+l-) > 110 && Pt > 38                        --> 48  fb
 had M(l+l-) > 110 && Pt > 50                        --> 32  fb
 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 23  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 18  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 12  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 15  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 10  fb


 had M(l+l-) > 400             -->  3.2 fb
 had M(l+l-) > 400 && Pt > 33  -->  2.3 fb
 had M(l+l-) > 400 && Pt > 38  -->  2.2 fb
 had M(l+l-) > 400 && Pt > 50  --> 1.9 fb
** electron 
*** Elastic production
1e6 events with E>3 Pt>1 for both (401pb):
318 had M(l+l-) > 110           --> 128 fb
66 had M(l+l-) > 110 && Pt > 33 --> 26  fb
49 had M(l+l-) > 110 && Pt > 38 --> 20  fb
49 had M(l+l-) > 110 && Pt > 50 --> 20  fb

0 had M(l+l-) > 400
0 had M(l+l-) > 400 && Pt > 33
0 had M(l+l-) > 400 && Pt > 38
0 had M(l+l-) > 400 && Pt > 50

5e5 events with *E>20 Pt>10* for both (1.28pb):
 had M(l+l-) > 110                                   --> 74 fb
 had M(l+l-) > 110 + Pt > 33                         --> 38  fb
 had M(l+l-) > 110 + Pt > 38                         --> 33  fb
 had M(l+l-) > 110 + Pt > 50                         --> 22  fb
 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 17  fb
 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 22  fb
  had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 17  fb
  had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 22  fb
  had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 17  fb


 had M(l+l-) > 400             --> 2.4 fb
 had M(l+l-) > 400 && Pt > 33  --> 1.6 fb
 had M(l+l-) > 400 && Pt > 38  --> 1.6 fb
 had M(l+l-) > 400 && Pt > 50  --> 1.2 fb
*** Disassociating production
1e6 events with *E>20 Pt>10* for both (1.4pb):
82227 had M(l+l-) > 110                                   --> 115 fb
40678 had M(l+l-) > 110 + Pt > 33                         --> 57  fb
34604 had M(l+l-) > 110 + Pt > 38                         --> 48  fb
22282 had M(l+l-) > 110 + Pt > 50                         --> 31  fb
16716 had M(l+l-) > 110 + Pt > 50 + eta < 2.4             --> 23  fb
10915 had M(l+l-) > 110 + Pt > 50 + a < 0.009             --> 15  fb
8195  had M(l+l-) > 110 + Pt > 50 + a < 0.009 + eta < 2.4 --> 11  fb
9874  had M(l+l-) > 110 + Pt > 50 + a < 0.006             --> 14  fb
7367  had M(l+l-) > 110 + Pt > 50 + a < 0.006 + eta < 2.4 --> 10  fb


2429 had M(l+l-) > 400             --> 3.4 fb
1640 had M(l+l-) > 400 && Pt > 33  --> 2.3 fb
1529 had M(l+l-) > 400 && Pt > 38  --> 2.1 fb
1232 had M(l+l-) > 400 && Pt > 50  --> 1.7 fb
* Cross sections (pb)
** electrons:
No Cuts:               6.82e9
Mode 2: E > 3, Pt > 1: 380
Mode 3: E > 3, Pt > 1: 788

PMod 11:
No Cuts:               128266
Mode 2: E > 3, Pt > 1: 170
Mode 3: E > 3, Pt > 1: 1812

** muons:
No Cuts:               144370
Mode 2: E > 3, Pt > 1: 405
Mode 3: E > 3, Pt > 1: 745

PMod 11:
No Cuts:               10336
Mode 2: E > 3, Pt > 1: 173
Mode 3: E > 3, Pt > 1: 1006

** taus: 
Elastic:
No Cuts:               213
Mode 2: E > 3, Pt > 1: 125
Mode 3: E > 3, Pt > 1: 154

PMod 11:
No Cuts:               133
Mode 2: E > 3, Pt > 1: 80
Mode 3: E > 3, Pt > 1: 116

* Parameters 
*AXOHS parameters*
Keyword Default Explanations:
IBEG            the starting step of the program:
        times   1: to run a completely new job
                2: to use the grid produced by VEGAS from a previous run
                3: to use the VEGAS grid and the information about the
		weights of events produced by SETGEN in a previous run
IEND            the concluding step of the program:
                1: to estimate the cross-section only
		2: to save SETGEN information (for further runs)
	times   3: to produce a complete output event (to be stored)
PRVG    1       Print parameter from VEGAS
NTRT    1       Strategy parameter NTREAT from VEGAS
NCVG    14000   Number of events for VEGAS to perform the integration
ITVG    10      Number of iterations for VEGAS
NCSG    100     Number of events in each bin (for SETGEN)
*Beam, particle and interaction parameters*
INPP    820     first incoming particle momentum in GeV/c
PMOD            first incoming particle type and kind of interaction:
                1: electron (for tests)
                2: proton elastic = default
		11: proton inelastic with structure functions [5]
		12: proton inelastic with structure functions [6] (for
		Mx < 2 GeV; Q^2 < 5 (GeV) )
		13:
		101: proton inelastic in parton model, only valence quarks
		102: proton inelastic in parton model, only sea quarks
		103: proton inelastic in parton model, valence and sea quarks
*Cut parameters*
MCUT    2       0: No cuts at all (for the total cross section)
                1: Vermaserens hypothetical detector cuts (see [2])
                2: Cut with the following parameters for both leptons
		3: Cut with the following parameters for one lepton only
THMX    175.0   max of lepton (in degrees)
THMN    5.0     min of lepton (in degrees)
ECUT    1.0     minimal energy of lepton (in GeV)
PTCT    0.5     minimal transverse momentum of lepton (in GeV)
Q2MN    0.0     minimal Q2 at the proton side (in GeV^2)
Q2MX    10000.  maximal Q2 at the proton side (in GeV^2)
for PMOD> 10 only :
MXMN    1.070   minimal inv. mass of the hadronic system (in GeV )
MXMX    320.0   maximal inv. mass of the hadronic system (in GeV )

* Info CMS-Totem Paper 
13 TeV Protons, 9.4fb^-1, 12 muons, 8 electrons
Online cut for mu(e) pt > 38(33) GeV
Offline cut for pt > 50GeV, chi^2 < 10, and standard CMS quality criteria

Require no additional tracks found withing the veto distance around the vertex
acoplanarity(a=1-abs(delta phi(l+l-))/Pi) required to be consistent with back to back
Cut on these two were chosen to minimize Drell-Yan background --> mu(e) a <0.009 (0.006), d = 0.5mm
m(l+l-) > 110 GeV

Gap survival probabilities are 0.89, 0.76, and 0.13, applied to the exclusive,
the single dissociative, and the double dissociative processes, respectively. The rapidity gap
survival probability quantifies the fraction of events in which no extra soft interactions occur
between the colliding protons. These soft interactions produce extra final-state particles, and
thereby suppress the visible (semi)exclusive cross section

Events with 1 good proton track in CT-PPS are kept
fractional mom. loss is estimated as 1/root(s) *(pt(l+)exp(-+eta(l+))+pt(l-)exp(-+eta(l-)))
where eta +- corresponds to proton moving in +-z
This is exact for exclusive, and holds for single-dissociation

Require fractional mom loss within CT-PPS coverage:
sector 45, RP 210N: frac > 0.033
sector 45, RP 210F: frac > 0.024
sector 56, RP 210N: frac > 0.042
sector 56, RP 210F: frac > 0.032

Finally, require frac of leptons and frac of RP agree within 2 sigma of their
combined uncertainty

* <2018-08-20 Mon>
Reran the events.root files through the myTreeMaker.C with the directories setup
Much more organized, but left the naming of the histograms/trees the same
* <2018-08-16 Thu>
Added a git repository for the project, under tau-g-minus-2 directory
* <2018-08-09 Thu>
Added a second mass histogram, with a lower range for low mass regions
Added to the hstackMaker.C script so that it creates png files for each
of the histograms, with labels and a legend
* <2018-08-08 Wed>
Added Eta cuts to the myTreeMaker.C and corrected the acoplanarity definition
Generating muon sample with E>20 and Pt>10, failed at 8.6e5 events
Reran with 5e5 events instead

Running all flavors with E>20 Pt>10, with eta, pt, acoplane, and mass cuts

Muons have a combined cross section of ~27fb --> ~270events in 10fb^-1
Electrons have a combined xsec of ~ 27fb as well --> ~270 events

--> veto distance cut, RP agreement cut, RP acceptance, lepton reconstruction/quality, 
chi^2 cut seem to cut 95-97% of events

consider veto distance, chi^2, and lepton recon cutting very little, since plot shows veto not cutting much
and 50GeV Pt leptons are reconstructed well

This implies RP acceptance and aggreement is ~ 5% efficient

ooking at figure 9 in the CMS-Totem paper, it looks like they see ~260 muon events and ~170 electron events
when simulating 15.6 fb^-1, before adding in RP cuts
for 15.6fb^-1, I expect ~420 events, and with effective gap survival of ~.83 --> ~350 events

Added a fractional momentum loss cut to myTreeMaker.C, added another factor of 2 --> RP reconstruction
and agreement is now looking like ~10% efficient

Generated hstacks with hstackMaker.C, and they look fairly similar to the ones
in figure 9 of the paper.

Mayda suggested we'd be looking at the lower invariant mass portion of the spectrum
Question would be what does the background look like there, and how well can we measure
something there. 

* <2018-08-07 Tue>

Continued generating lepton root files, and looking and cross section after cuts
With the Pt and Mass cuts, all leptons had similar cross section left
With ~ 60fb for muon/electron, ~ 10 fb^-1, expect 600 of each
If acoplane goes the same for elastic and muons, expect ~ 400 events
This implies the proton requirements, the mismatch, the veto distance, and
reconstruction efficiencies are about a 97% cut? 

* <2018-08-06 Mon>
edited myTreeMaker.C to include less info that can be derived (eta, pt, phi, etc)
Added lorentz vectors for proton1/2, gamma1/2, tau1/2, and tau(gamma) system
Generated 1e6 tau events (elastic) and W looked similar to starlight

Looked at dissociating protons (just 1) and that cross section

Added here some information about the kinematics of pairs looked at in the
muon and electron lepton pairs paper

Added multiple trees to myTreeMaker.C and an include file

Reran the elastic proton case with 1e6 events

* <2018-08-03 Fri>
Worked on cross section + root tree maker
